### ISSUE TITLE
make generated html and pdf file available somewhere

### ISSUE THREAD

**Issue by fangohr** [fangohr/introduction-to-python-for-computational-science-and-engineering#3]
for convenience for those who are not familiar with git, make, docker, etc.

Options:
- either from continuous integration system
- or manually posted on some webpage

**Comment by fangohr** [comment]
For now, we just leave the pdf and html output in the repository. The easiest way to use it, is to download a zip file of the whole repository.

Would be nice to host the html elsewhere, so that it can be browsed like a static webpage.

**Comment by owlas** [comment]
If you don't mind a small name change, you could serve the HTML to gh-pages:

https://github.com/blog/2228-simpler-github-pages-publishing

**Comment by fangohr** [comment]
Ah, nice. So anything in the `docs` folder is served as static html? That's good.

**Comment by owlas** [comment]
Yeah it's a nice feature!  

Here is how it rendered on my fork: https://owlas.github.io/introduction-to-python-for-computational-science-and-engineering/

It ends up being a pretty long URL but you could point some other domain name at it https://stackoverflow.com/a/9123911/2261276

**Comment by fangohr** [comment]
HTML files can now be browsed online at https://fangohr.github.io/introduction-to-python-for-computational-science-and-engineering/
